DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(60) NOT NULL, APELLIDO VARCHAR(60) NOT NULL);

--creación de Odontologos inicial

INSERT INTO ODONTOLOGOS( MATRICULA, NOMBRE, APELLIDO ) VALUES(7733, 'Andrea', 'Romero'), (4411, 'Astrid', 'Torres'), (3332, 'Andres', 'Lopez');

